# Generated by Django 3.2.16 on 2022-10-18 02:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formul2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carne', models.TextField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^[A|a][a-zA-Z0-9][5][a-zA-Z0-9][a-zA-Z0-9][1|3|9]$')])),
                ('name', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('born', models.DateField()),
                ('carrera', models.CharField(max_length=50)),
                ('poesia', models.CharField(max_length=50)),
                ('insc', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
